{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClassName | default "azurefile-csi" }}
  volumeMode: Filesystem
{{- end }}
